[
	uuid("4556509F-618A-46CF-AB3D-ED736ED66477"),
	version(1.0)
]

interface RpcServerInterface
{
cpp_quote("#ifdef MIDL_COMPILE")
#ifdef UNICODE
	typedef wchar_t	TCHAR;
#else
	typedef char	TCHAR;
#endif

	typedef TCHAR *	LPTSTR;
cpp_quote("#endif")

	typedef enum _RPC_SERVER_STATUS
	{
		RPC_SERVER_STATUS_SUCCESS,
		RPC_SERVER_STATUS_FAILED
	} RPC_SERVER_STATUS, *PRPC_SERVER_STATUS, *LPRPC_SERVER_STATUS;

	RPC_SERVER_STATUS RpcTest([in, string] LPTSTR lpCh);
	RPC_SERVER_STATUS RpcUseCallback(void);
	RPC_SERVER_STATUS RpcStopServer(void);

	[callback] RPC_SERVER_STATUS RpcCallback([in, string] LPTSTR lpCh);
}
